// templates/connect-chain/components/wallet/Wallet.tsx
import {
  Box,
  ClipboardCopyText,
  Stack,
  useColorModeValue,
} from "@interchain-ui/react";
import { WalletState as WalletStatus } from "@interchain-kit/core";
import { useChain } from "@interchain-kit/react";
import { getChainLogo } from "@/utils";
import { CHAIN_NAME } from "@/config";
import { User } from "./User";
import { Chain } from "./Chain";
import { Warning } from "./Warning";
import {
  ButtonConnect,
  ButtonConnected,
  ButtonConnecting,
  ButtonDisconnected,
  ButtonError,
  ButtonNotExist,
  ButtonRejected,
} from "./Connect";

export function Wallet() {
  const {
    chain,
    status,
    wallet,
    username,
    address,
    message,
    connect,
    openView,
  } = useChain(CHAIN_NAME);

  const ConnectButton = {
    [WalletStatus.Connected]: <ButtonConnected onClick={openView} />,
    [WalletStatus.Connecting]: <ButtonConnecting />,
    [WalletStatus.Disconnected]: <ButtonDisconnected onClick={connect} />,
    // [WalletStatus.Error]: <ButtonError onClick={openView} />,
    [WalletStatus.Rejected]: <ButtonRejected onClick={connect} />,
    // [WalletStatus.NotExist]: <ButtonNotExist onClick={openView} />,
  }[status] || <ButtonConnect onClick={connect} />;

  return (
    <Box py="$16">
      <Stack attributes={{ mb: "$12", justifyContent: "center" }}>
        <Chain
          name={chain.prettyName!}
          logo={getChainLogo(chain.chainName)!}
        />
      </Stack>
      <Stack
        direction="vertical"
        attributes={{
          mx: "auto",
          px: "$8",
          py: "$15",
          maxWidth: "21rem",
          borderRadius: "$lg",
          justifyContent: "center",
          backgroundColor: useColorModeValue("$white", "$blackAlpha500"),
          boxShadow: useColorModeValue(
            "0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3",
            "0 0 2px #363636, 0 0 8px -2px #4f4f4f",
          ),
        }}
      >
        {username ? <User name={username} /> : null}
        {address
          ? <ClipboardCopyText text={address} truncate="middle" />
          : null}
        <Box
          my="$8"
          flex="1"
          width="full"
          display="flex"
          height="$16"
          overflow="hidden"
          justifyContent="center"
          px={{ mobile: "$8", tablet: "$10" }}
        >
          {ConnectButton}
        </Box>

        {message && [
          // WalletStatus.Error,
          WalletStatus.Rejected
        ].includes(status)
          ? <Warning text={`${wallet?.info?.prettyName}: ${message}`} />
          : null}
      </Stack>
    </Box>
  );
}

// examples/injective-vue/src/components/asset-list/wallet/wallet.vue
<script setup lang="ts">
import { Stack, Box } from "@interchain-ui/vue";
import ChainCard from "./chain-card.vue";
import { defineProps, ref, computed, watch } from "vue";
import { useChain } from "@interchain-kit/vue";
import { WalletState } from "@interchain-kit/core";
import { defaultChainName } from "@/config/asset-list/defaults";
import UserInfo from "./user-info.vue";
import ConnectWalletButton from "./wallet-connect/ConnectWalletButton.vue";
import CopyAddressBtn from "./copy-address-btn.vue";
import { useBalanceVue } from "../../../composables/injective/useBalanceVue";

defineProps({
  prettyName: String,
});

const chainName = ref(defaultChainName);
const chainInfo = useChain(chainName);
const { username, logoUrl, connect, status, address, openView } = chainInfo;

console.log("chainInfo", chainInfo, username);

let balanceVue: any;

if (address) {
  try {
    balanceVue = useBalanceVue(address);
  } catch (e) {
    console.log("error", e);
  }
}

const { balance, isBalanceLoaded, isFetchingBalance, refetchBalance } = balanceVue || {};

const handleWalletBtnClick = () => {
  if (status.value === WalletState.Disconnected) {
    connect.value();
  } else if (status.value === WalletState.Connected) {
    openView();
  } else {
    connect.value();
  }
};

const computedBalance = computed(() => {
  return balanceVue ? balanceVue.balance : null;
});

const buttonText = computed(() => {
  switch (status.value) {
    case WalletState.Disconnected || undefined:
      return "Connect Wallet";
    case WalletState.Connected:
      return "My Wallet";
    default:
      return "Connect Wallet";
  }
});
</script>

<template>
  <Box
    display="flex"
    justifyContent="center"
    alignItems="center"
    py="$12"
    width="100%"
    :attributes="{
      'data-part-id': 'wallet-section',
    }"
  >
    <Box
      display="grid"
      width="$full"
      :maxWidth="{
        mobile: '100%',
        tablet: '450px',
      }"
      gridTemplateColumns="1fr"
      rowGap="$10"
      alignItems="center"
      justifyContent="center"
    >
      <Box marginBottom="$9">
        <ChainCard :prettyName="defaultChainName" :icon="logoUrl" />
      </Box>

      <Box :px="6">
        <Stack
          direction="vertical"
          :attributes="{
            px: '$2',
            py: '$12',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '$lg',
            backgroundColor: '$white',
            boxShadow: '0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3',
          }"
          space="$8"
        >
          <UserInfo :username="username" />
          <!-- {addressBtn} -->
          <CopyAddressBtn :address="address" />
          <Box width="100%" maxWidth="200px" :attributes="{ id: 'connect-button' }">
            <ConnectWalletButton
              :button-text="buttonText"
              @click="handleWalletBtnClick"
            />
          </Box>

          <!-- {connectWalletWarn} -->
        </Stack>
      </Box>

      <Box v-if="isBalanceLoaded" :attributes="{ fontWeight: 'bold' }">
        Balance: {{ computedBalance }}
      </Box>
    </Box>
  </Box>
</template>

<style scoped></style>
