// examples/ibc-asset-list/components/wallet/Wallet.tsx
import { useChain } from '@interchain-kit/react';
import { Box, Stack, useTheme } from '@interchain-ui/react';
import { MouseEventHandler, useEffect, useMemo } from 'react';
import { FiAlertTriangle } from 'react-icons/fi';
import { chains } from '@chain-registry/v2';

import { defaultChainName } from '@/config';
import {
  Connected,
  Connecting,
  Disconnected,
  NotExist,
  Error,
  Rejected,
  WalletConnectComponent,
  ConnectWalletButton,
} from './WalletConnect';
import { ConnectStatusWarn, RejectedWarn } from './WarnBlock';
import { ChooseChain, ChooseChainProps } from './ChooseChain';
import { ConnectedShowAddress, CopyAddressBtn } from './AddressCard';
import { UserInfo } from './UserInfo';
import { Astronaut } from './Astronaut';
import { ChainCard } from './ChainCard';

export interface WalletSectionProps {
  isMultiChain: boolean;
  providedChainName?: string;
  setChainName?: (chainName: string | undefined) => void;
}

export const WalletSection = ({
  isMultiChain,
  providedChainName,
  setChainName,
}: WalletSectionProps) => {
  const {
    connect,
    openView,
    status,
    username,
    address,
    message,
    wallet,
    chain: chainInfo,
  } = useChain(providedChainName || defaultChainName);

  const { theme } = useTheme();

  const chain = {
    chainName: defaultChainName,
    label: chainInfo.prettyName,
    value: defaultChainName,
    icon: chains.find(c => c.chainName === defaultChainName)?.logoURIs?.png // getChainLogo(defaultChainName),
  };

  const chainOptions = useMemo(
    () =>
      chains.map((chainRecord) => {
        return {
          chainName: chainRecord?.chainName,
          label: chainRecord?.prettyName!,
          value: chainRecord?.chainName,
          icon: chainRecord.logoURIs?.png
        };
      }),
    []
  );

  // Events
  const onClickConnect: MouseEventHandler = async (e) => {
    e.preventDefault();
    await connect();
  };

  const onClickOpenView: MouseEventHandler = (e) => {
    e.preventDefault();
    openView();
  };

  // Components
  const connectWalletButton = (
    <WalletConnectComponent
      // @ts-ignore
      walletStatus={status}
      disconnect={
        <Disconnected buttonText="Connect Wallet" onClick={onClickConnect} />
      }
      connecting={<Connecting />}
      connected={
        <Connected buttonText={'My Wallet'} onClick={onClickOpenView} />
      }
      rejected={<Rejected buttonText="Reconnect" onClick={onClickConnect} />}
      error={<Error buttonText="Change Wallet" onClick={onClickOpenView} />}
      notExist={
        <NotExist buttonText="Install Wallet" onClick={onClickOpenView} />
      }
    />
  );

  const connectWalletWarn = message ? (
    <ConnectStatusWarn
      // @ts-ignore
      walletStatus={status}
      rejected={
        <RejectedWarn
          icon={
            <Box mt="$2">
              <FiAlertTriangle />
            </Box>
          }
          wordOfWarning={`${wallet?.info?.prettyName}: ${message}`}
        />
      }
      error={
        <RejectedWarn
          icon={
            <Box mt="$2">
              <FiAlertTriangle />
            </Box>
          }
          wordOfWarning={`${wallet?.info?.prettyName}: ${message}`}
        />
      }
    />
  ) : null;

  useEffect(() => {
    setChainName?.(
      window.localStorage.getItem('selected-chain') || defaultChainName
    );
  }, [setChainName]);

  const onChainChange: ChooseChainProps['onChange'] = async (selectedValue) => {
    if (!selectedValue) return;

    if (selectedValue?.value) {
      setChainName?.(selectedValue?.value);
      window?.localStorage.setItem('selected-chain', selectedValue?.value);
    } else {
      window?.localStorage.removeItem('selected-chain');
    }
  };

  const chooseChain = (
    <ChooseChain
      chainName={providedChainName}
      chainInfos={chainOptions}
      onChange={onChainChange}
    />
  );

  const userInfo = username && (
    <UserInfo username={username} icon={<Astronaut />} />
  );

  const addressBtn = (
    <CopyAddressBtn
      walletStatus={status}
      connected={<ConnectedShowAddress address={address} isLoading={false} />}
    />
  );

  return (
    <Box
      display="flex"
      justifyContent="center"
      alignItems="center"
      py="$12"
      width="100%"
      attributes={{
        'data-part-id': 'wallet-section',
      }}
    >
      <Box
        display="grid"
        width="$full"
        maxWidth={{
          mobile: '100%',
          tablet: '450px',
        }}
        gridTemplateColumns="1fr"
        rowGap="$10"
        alignItems="center"
        justifyContent="center"
      >
        {isMultiChain ? (
          <Box>{chooseChain}</Box>
        ) : (
          <Box marginBottom={'$9'}>
            <ChainCard
              prettyName={chain?.label || defaultChainName}
              icon={chain?.icon}
            />
          </Box>
        )}

        {!providedChainName && isMultiChain ? (
          <ConnectWalletButton buttonText={'Connect Wallet'} isDisabled />
        ) : (
          <Box px={6}>
            <Stack
              direction="vertical"
              attributes={{
                px: '$2',
                py: '$12',
                justifyContent: 'center',
                alignItems: 'center',
                borderRadius: '$lg',
                backgroundColor: theme === 'light' ? '$white' : '$cardBg',
                boxShadow:
                  theme === 'light'
                    ? '0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3'
                    : '0 0 2px #363636, 0 0 8px -2px #4f4f4f',
              }}
              space="$8"
            >
              {userInfo}
              {addressBtn}

              <Box
                width="100%"
                maxWidth="200px"
                attributes={{ id: 'connect-button' }}
              >
                {connectWalletButton}
              </Box>

              {connectWalletWarn}
            </Stack>
          </Box>
        )}
      </Box>
    </Box>
  );
};

// examples/injective-vue/src/components/asset-list/wallet/wallet.vue
<script setup lang="ts">
import { Stack, Box } from "@interchain-ui/vue";
import ChainCard from "./chain-card.vue";
import { defineProps, ref, computed, watch } from "vue";
import { useChain } from "@interchain-kit/vue";
import { WalletState } from "@interchain-kit/core";
import { defaultChainName } from "@/config/asset-list/defaults";
import UserInfo from "./user-info.vue";
import ConnectWalletButton from "./wallet-connect/ConnectWalletButton.vue";
import CopyAddressBtn from "./copy-address-btn.vue";
import { useBalanceVue } from "../../../composables/injective/useBalanceVue";

defineProps({
  prettyName: String,
});

const chainName = ref(defaultChainName);
const chainInfo = useChain(chainName);
const { username, logoUrl, connect, status, address, openView } = chainInfo;

console.log("chainInfo", chainInfo, username);

let balanceVue: any;

if (address) {
  try {
    balanceVue = useBalanceVue(address);
  } catch (e) {
    console.log("error", e);
  }
}

const { balance, isBalanceLoaded, isFetchingBalance, refetchBalance } = balanceVue || {};

const handleWalletBtnClick = () => {
  if (status.value === WalletState.Disconnected) {
    connect.value();
  } else if (status.value === WalletState.Connected) {
    openView();
  } else {
    connect.value();
  }
};

const computedBalance = computed(() => {
  return balanceVue ? balanceVue.balance : null;
});

const buttonText = computed(() => {
  switch (status.value) {
    case WalletState.Disconnected || undefined:
      return "Connect Wallet";
    case WalletState.Connected:
      return "My Wallet";
    default:
      return "Connect Wallet";
  }
});
</script>

<template>
  <Box
    display="flex"
    justifyContent="center"
    alignItems="center"
    py="$12"
    width="100%"
    :attributes="{
      'data-part-id': 'wallet-section',
    }"
  >
    <Box
      display="grid"
      width="$full"
      :maxWidth="{
        mobile: '100%',
        tablet: '450px',
      }"
      gridTemplateColumns="1fr"
      rowGap="$10"
      alignItems="center"
      justifyContent="center"
    >
      <Box marginBottom="$9">
        <ChainCard :prettyName="defaultChainName" :icon="logoUrl" />
      </Box>

      <Box :px="6">
        <Stack
          direction="vertical"
          :attributes="{
            px: '$2',
            py: '$12',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '$lg',
            backgroundColor: '$white',
            boxShadow: '0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3',
          }"
          space="$8"
        >
          <UserInfo :username="username" />
          <!-- {addressBtn} -->
          <CopyAddressBtn :address="address" />
          <Box width="100%" maxWidth="200px" :attributes="{ id: 'connect-button' }">
            <ConnectWalletButton
              :button-text="buttonText"
              @click="handleWalletBtnClick"
            />
          </Box>

          <!-- {connectWalletWarn} -->
        </Stack>
      </Box>

      <Box v-if="isBalanceLoaded" :attributes="{ fontWeight: 'bold' }">
        Balance: {{ computedBalance }}
      </Box>
    </Box>
  </Box>
</template>

<style scoped></style>
