// examples/injective-vue/src/components/asset-list/wallet/wallet.vue
<script setup lang="ts">
import { Stack, Box } from "@interchain-ui/vue";
import ChainCard from "./chain-card.vue";
import { defineProps, ref, computed, watch } from "vue";
import { useChain } from "@interchain-kit/vue";
import { WalletState } from "@interchain-kit/core";
import { defaultChainName } from "@/config/asset-list/defaults";
import UserInfo from "./user-info.vue";
import ConnectWalletButton from "./wallet-connect/ConnectWalletButton.vue";
import CopyAddressBtn from "./copy-address-btn.vue";
import { useBalanceVue } from "../../../composables/injective/useBalanceVue";

defineProps({
  prettyName: String,
});

const chainName = ref(defaultChainName);
const chainInfo = useChain(chainName);
const { username, logoUrl, connect, status, address, openView } = chainInfo;

console.log("chainInfo", chainInfo, username);

const balanceVue = useBalanceVue(chainName);


const { balance, isBalanceLoaded, isFetchingBalance, refetchBalance } = balanceVue || {};

const handleWalletBtnClick = () => {
  if (status.value === WalletState.Disconnected) {
    connect.value();
  } else if (status.value === WalletState.Connected) {
    openView();
  } else {
    connect.value();
  }
};

const computedBalance = computed(() => {
  return balanceVue ? balanceVue.balance : null;
});

const buttonText = computed(() => {
  switch (status.value) {
    case WalletState.Disconnected || undefined:
      return "Connect Wallet";
    case WalletState.Connected:
      return "My Wallet";
    default:
      return "Connect Wallet";
  }
});
</script>

<template>
  <Box
    display="flex"
    justifyContent="center"
    alignItems="center"
    py="$12"
    width="100%"
    :attributes="{
      'data-part-id': 'wallet-section',
    }"
  >
    <Box
      display="grid"
      width="$full"
      :maxWidth="{
        mobile: '100%',
        tablet: '450px',
      }"
      gridTemplateColumns="1fr"
      rowGap="$10"
      alignItems="center"
      justifyContent="center"
    >
      <Box marginBottom="$9">
        <ChainCard :prettyName="defaultChainName" :icon="logoUrl" />
      </Box>

      <Box :px="6">
        <Stack
          direction="vertical"
          :attributes="{
            px: '$2',
            py: '$12',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '$lg',
            backgroundColor: '$white',
            boxShadow: '0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3',
          }"
          space="$8"
        >
          <UserInfo :username="username" />
          <!-- {addressBtn} -->
          <CopyAddressBtn :address="address" />
          <Box width="100%" maxWidth="200px" :attributes="{ id: 'connect-button' }">
            <ConnectWalletButton
              :button-text="buttonText"
              @click="handleWalletBtnClick"
            />
          </Box>

          <!-- {connectWalletWarn} -->
        </Stack>
      </Box>

      <Box v-if="isBalanceLoaded" :attributes="{ fontWeight: 'bold' }">
        Balance: {{ computedBalance }}
      </Box>
    </Box>
  </Box>
</template>

<style scoped></style>

// examples/injective/components/wallet/Wallet.tsx
import { Box, Stack, ClipboardCopyText, useColorModeValue } from '@interchain-ui/react';
import { WalletState } from '@interchain-kit/core'
import { useChain } from '@interchain-kit/react';
import { getChainLogo } from '@/utils';
import { defaultChainName } from "@/config";
import { User } from './User';
import { Chain } from './Chain';
import { Button } from './Connect';
import { Warning } from './Warning';

export function Wallet() {
  const { chain, status, wallet, username, address, message, connect, openView } = useChain(defaultChainName);

  const ConnectButton = {
    [WalletState.Connected]: <Button.Connected onClick={openView} />,
    [WalletState.Connecting]: <Button.Connecting />,
    [WalletState.Disconnected]: <Button.Disconnected onClick={openView} />,
    [WalletState.Rejected]: <Button.Rejected onClick={openView} />,
    [WalletState.NotExist]: <Button.Disconnected onClick={openView} />,
  }[status] || <Button.Connect onClick={openView} />;

  return (
    <Box py="$16">
      <Stack attributes={{ mb: '$12', justifyContent: 'center' }}>
        <Chain name={chain.prettyName || 'prettyName unknown'} logo={getChainLogo(chain.chainName)!} />
      </Stack>
      <Stack
        direction="vertical"
        attributes={{
          mx: 'auto',
          px: '$8',
          py: '$15',
          maxWidth: '21rem',
          borderRadius: '$lg',
          justifyContent: 'center',
          backgroundColor: useColorModeValue('$white', '$blackAlpha500'),
          boxShadow: useColorModeValue(
            '0 0 2px #dfdfdf, 0 0 6px -2px #d3d3d3',
            '0 0 2px #363636, 0 0 8px -2px #4f4f4f'
          )
        }}
      >
        {username ? <User name={username} /> : null}
        {address ? <ClipboardCopyText text={address} truncate="middle" /> : null}
        <Box
          my="$8"
          flex="1"
          width="full"
          display="flex"
          height="$16"
          overflow="hidden"
          justifyContent="center"
          px={{ mobile: '$8', tablet: '$10' }}>
          {ConnectButton}
        </Box>

        {message && [WalletState.Rejected].includes(status)
          ? <Warning text={`${wallet?.info?.name}: ${message}`} />
          : null}
      </Stack>
    </Box>
  )
}
